version: '3'
services:
  artifactory:
    build: .
    container_name: artifactory
    ports:
      - "8082:8082" # for router communication
      - "8081:8081" # for artifactory communication
    volumes:
      - /srv/data.vol/jfrog:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"

